# Generated by Django 5.2.8 on 2025-12-06 12:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.IntegerField(unique=True, verbose_name='회차')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='과목명')),
                ('code', models.IntegerField(unique=True, verbose_name='과목 코드')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='문제 번호')),
                ('content', models.TextField(verbose_name='문제 지문')),
                ('image', models.ImageField(blank=True, null=True, upload_to='questions/images/', verbose_name='문제 이미지')),
                ('choice1', models.CharField(max_length=200, verbose_name='보기 1')),
                ('choice2', models.CharField(max_length=200, verbose_name='보기 2')),
                ('choice3', models.CharField(max_length=200, verbose_name='보기 3')),
                ('choice4', models.CharField(max_length=200, verbose_name='보기 4')),
                ('choice5', models.CharField(max_length=200, verbose_name='보기 5')),
                ('answer', models.IntegerField(verbose_name='정답 (1-5)')),
                ('explanation', models.TextField(verbose_name='해설')),
                ('explanation_image', models.ImageField(blank=True, null=True, upload_to='questions/explanations/', verbose_name='해설 이미지')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='exam.exam')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='exam.subject')),
            ],
            options={
                'ordering': ['exam', 'number'],
                'unique_together': {('exam', 'number')},
            },
        ),
        migrations.CreateModel(
            name='UserExamAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='시작 시간')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='종료 시간')),
                ('total_score', models.IntegerField(blank=True, null=True, verbose_name='총점')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.exam')),
                ('subjects', models.ManyToManyField(to='exam.subject', verbose_name='응시 과목')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_attempts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserQuestionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_choice', models.IntegerField(verbose_name='선택 답안')),
                ('is_correct', models.BooleanField(verbose_name='정답 여부')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='exam.userexamattempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.question')),
            ],
        ),
    ]
