# Generated by Django 5.2.8 on 2025-12-14 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_rename_explanation_image_to_infographic_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='explanation',
            new_name='general_chat',
        ),
        migrations.AddField(
            model_name='question',
            name='textbook_chat',
            field=models.TextField(blank=True, null=True, verbose_name='기본서 해설'),
        ),
    ]
