# Generated by Django 5.2.8 on 2025-12-21 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_rename_explanation_question_general_chat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userexamattempt',
            name='ai_analysis',
            field=models.TextField(blank=True, null=True, verbose_name='AI 분석 리포트'),
        ),
    ]
