# Generated by Django 6.0 on 2025-12-25 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0004_userexamattempt_ai_analysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='narration',
            field=models.TextField(blank=True, null=True, verbose_name='나레이션'),
        ),
    ]
