# Generated by Django 5.2.8 on 2025-12-26 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0005_question_narration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.JSONField(default=list, verbose_name='정답 (1-5, 복수 가능)'),
        ),
    ]
