# Generated by Django 5.2.8 on 2026-01-14 07:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0006_alter_question_answer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicQuestionSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='문제집 제목')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('is_public', models.BooleanField(default=True, verbose_name='공개 여부')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_sets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '주제별 문제집',
                'verbose_name_plural': '주제별 문제집',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserTopicSetAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='시작 시간')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='종료 시간')),
                ('total_score', models.IntegerField(blank=True, null=True, verbose_name='총점')),
                ('question_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.topicquestionset')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '주제별 문제집 응시',
                'verbose_name_plural': '주제별 문제집 응시',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='UserTopicQuestionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_choice', models.IntegerField(verbose_name='선택 답안')),
                ('is_correct', models.BooleanField(verbose_name='정답 여부')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.question')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='exam.usertopicsetattempt')),
            ],
            options={
                'verbose_name': '주제별 문제 결과',
                'verbose_name_plural': '주제별 문제 결과',
            },
        ),
        migrations.CreateModel(
            name='TopicQuestionSetItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(verbose_name='순서')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.question')),
                ('question_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='exam.topicquestionset')),
            ],
            options={
                'verbose_name': '문제집 항목',
                'verbose_name_plural': '문제집 항목',
                'ordering': ['order'],
                'unique_together': {('question_set', 'order')},
            },
        ),
    ]
