# Generated by Django 5.2.8 on 2026-01-15 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0007_topicquestionset_usertopicsetattempt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='summary',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='문제 요약'),
        ),
    ]
