# Generated by Django 5.2.8 on 2026-01-17 01:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0008_add_summary_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='topicquestionset',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='topic_sets', to='exam.subject', verbose_name='과목'),
        ),
    ]
