# Generated by Django 5.2.8 on 2026-01-17 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0009_add_subject_to_topicset'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topicquestionset',
            options={'ordering': ['order', '-created_at'], 'verbose_name': '주제별 문제집', 'verbose_name_plural': '주제별 문제집'},
        ),
        migrations.AddField(
            model_name='topicquestionset',
            name='order',
            field=models.IntegerField(default=0, verbose_name='정렬 순서'),
        ),
    ]
