# Generated by Django 6.0 on 2026-03-01 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0010_alter_topicquestionset_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='general_chat',
            field=models.TextField(blank=True, default='', verbose_name='해설'),
        ),
        migrations.CreateModel(
            name='StudyNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('content', models.TextField(verbose_name='내용')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='순서')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_notes', to='exam.subject', verbose_name='과목')),
            ],
            options={
                'verbose_name': '쪽집게 노트',
                'verbose_name_plural': '쪽집게 노트',
                'ordering': ['subject', 'order'],
                'unique_together': {('subject', 'order')},
            },
        ),
    ]
