# Generated by Django 6.0 on 2026-08-25 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0011_alter_question_general_chat_studynote'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='choice_notes',
            field=models.JSONField(blank=True, default=dict, help_text='보기 번호를 키로 쓴다. 예: {"1": "…", "2": "…"}', verbose_name='선지별 설명'),
        ),
    ]
