# Generated by Django 6.0 on 2026-08-27 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0013_merge_20260825_1952'),
        ('practice', '0003_chapterpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='topicquestionset',
            name='chapter',
            field=models.ForeignKey(blank=True, help_text='목차를 고르면 그 목차 상세 화면에 기출문제풀이가 나온다', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='topic_sets', to='practice.chapter', verbose_name='목차'),
        ),
    ]
