# Generated by Django 6.0 on 2026-08-13 11:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exam', '0011_alter_question_general_chat_studynote'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture_date', models.DateField(verbose_name='일시')),
                ('period', models.IntegerField(default=1, verbose_name='교시')),
                ('title', models.CharField(max_length=200, verbose_name='내용')),
                ('duration_min', models.IntegerField(default=0, help_text='0이면 표시하지 않는다', verbose_name='시간(분)')),
                ('video_url', models.URLField(help_text='네이버 등에 올린 주소 (예: https://naver.me/FvTbwUsX)', max_length=500, verbose_name='영상 링크')),
                ('note', models.TextField(blank=True, default='', verbose_name='비고')),
                ('is_active', models.BooleanField(default=True, verbose_name='공개')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_lectures', to=settings.AUTH_USER_MODEL, verbose_name='등록자')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lectures', to='exam.subject', verbose_name='과목')),
            ],
            options={
                'verbose_name': '녹화강의',
                'verbose_name_plural': '녹화강의',
                'ordering': ['-lecture_date', 'period', 'id'],
            },
        ),
    ]
