# Generated by Django 6.0 on 2026-08-13 11:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LectureView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0, verbose_name='시청 횟수')),
                ('first_viewed_at', models.DateTimeField(auto_now_add=True, verbose_name='처음 시청')),
                ('last_viewed_at', models.DateTimeField(auto_now=True, verbose_name='마지막 시청')),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='lecture.lecture', verbose_name='강의')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecture_views', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '녹화강의 시청',
                'verbose_name_plural': '녹화강의 시청',
                'ordering': ['-last_viewed_at'],
                'unique_together': {('lecture', 'user')},
            },
        ),
    ]
