# Generated by Django 5.2.8 on 2025-12-20 08:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0001_initial'),
        ('notebook', '0002_notebookhistory_subject'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyQnA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q_type', models.CharField(choices=[('notebook', 'Notebook'), ('chat', 'Chat')], max_length=20, verbose_name='질문 유형')),
                ('question', models.TextField(verbose_name='질문 내용')),
                ('answer', models.TextField(verbose_name='답변 내용')),
                ('is_public', models.BooleanField(default=False, verbose_name='공개 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일시')),
                ('related_chat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='study_qna_entries', to='chat.chathistory')),
                ('related_notebook', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='study_qna_entries', to='notebook.notebookhistory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_qnas', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '학습 질의응답',
                'verbose_name_plural': '학습 질의응답 목록',
                'ordering': ['-created_at'],
            },
        ),
    ]
