# Generated by Django 5.2.8 on 2025-12-26 06:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyViewLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_round', models.IntegerField(verbose_name='회차')),
                ('viewed_at', models.DateTimeField(auto_now_add=True, verbose_name='열람 시간')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_view_logs', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '학습 열람 기록',
                'verbose_name_plural': '학습 열람 기록',
                'ordering': ['-viewed_at'],
            },
        ),
    ]
