# Generated by Django 6.0 on 2026-03-03 03:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0011_alter_question_general_chat_studynote'),
        ('study', '0002_studyviewlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('textbook_possible', models.BooleanField(default=True, verbose_name='교과서 풀이 가능')),
                ('textbook_reason', models.TextField(blank=True, default='', verbose_name='근거')),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='exam.question', verbose_name='문항')),
            ],
            options={
                'verbose_name': '문항 분석',
                'verbose_name_plural': '문항 분석',
            },
        ),
        migrations.CreateModel(
            name='RoundAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('past_exam_data', models.JSONField(default=dict, verbose_name='기출 학습 분석 데이터')),
                ('past_exam_avg_score', models.IntegerField(verbose_name='기출 학습 평균 예상 점수')),
                ('textbook_avg_score', models.FloatField(verbose_name='교과서 평균 예상 점수')),
                ('summary', models.TextField(blank=True, verbose_name='분석 요약')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('exam', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='exam.exam', verbose_name='회차')),
            ],
            options={
                'verbose_name': '회차별 분석',
                'verbose_name_plural': '회차별 분석',
            },
        ),
    ]
