# Generated by Django 6.0 on 2026-03-03 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0003_questionanalysis_roundanalysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='roundanalysis',
            name='detail_content',
            field=models.JSONField(blank=True, default=dict, verbose_name='상세 분석 콘텐츠'),
        ),
    ]
