# Generated by Django 6.0 on 2026-08-02 13:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiseaseCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='코스명')),
                ('description', models.CharField(blank=True, default='', max_length=200, verbose_name='설명')),
                ('order', models.IntegerField(default=0, verbose_name='정렬 순서')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '병해 식별 코스',
                'verbose_name_plural': '병해 식별 코스',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DiseaseQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='diseaseid/', verbose_name='병해 사진')),
                ('order', models.IntegerField(default=0, verbose_name='순번')),
                ('name', models.CharField(blank=True, default='', max_length=200, verbose_name='병명')),
                ('host', models.CharField(blank=True, default='', max_length=200, verbose_name='기주')),
                ('pathogen', models.CharField(blank=True, default='', max_length=300, verbose_name='병원균')),
                ('note', models.CharField(blank=True, default='', max_length=300, verbose_name='추가사항')),
                ('taxonomy', models.CharField(blank=True, default='', max_length=200, verbose_name='분류')),
                ('alt_host', models.CharField(blank=True, default='', max_length=200, verbose_name='중간기주')),
                ('exam_stars', models.IntegerField(db_index=True, default=0, verbose_name='기출 중요도')),
                ('exam_note', models.CharField(blank=True, default='', max_length=200, verbose_name='기출 회차')),
                ('source_key', models.CharField(blank=True, db_index=True, default='', max_length=200, verbose_name='원본 식별자')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='diseaseid.diseasecourse', verbose_name='코스')),
            ],
            options={
                'verbose_name': '병해 식별 문제',
                'verbose_name_plural': '병해 식별 문제',
                'ordering': ['course', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DiseaseBookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록 시각')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disease_bookmarks', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='diseaseid.diseasequestion', verbose_name='문제')),
            ],
            options={
                'verbose_name': '관심 병해',
                'verbose_name_plural': '관심 병해',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'question')},
            },
        ),
    ]
