# Generated by Django 5.2.8 on 2026-01-17 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0002_posttype_post_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at']},
        ),
    ]
