# Generated by Django 5.2.8 on 2025-12-13 01:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_input', models.TextField(verbose_name='질문')),
                ('ai_response', models.TextField(verbose_name='답변')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일시')),
                ('response_time', models.FloatField(blank=True, null=True, verbose_name='응답시간(초)')),
                ('is_success', models.BooleanField(default=True, verbose_name='성공여부')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_histories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '채팅 기록',
                'verbose_name_plural': '채팅 기록 목록',
                'ordering': ['-created_at'],
            },
        ),
    ]
