# Generated by Django 5.2.8 on 2025-12-22 05:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exam', '0004_userexamattempt_ai_analysis'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_wrong_date', models.DateTimeField(verbose_name='마지막 오답 일시')),
                ('review_count', models.IntegerField(default=0, verbose_name='복습 횟수')),
                ('next_review_date', models.DateField(verbose_name='다음 복습 예정일')),
                ('is_mastered', models.BooleanField(default=False, verbose_name='완전 학습 여부')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_schedules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['next_review_date'],
                'unique_together': {('user', 'question')},
            },
        ),
    ]
