# Generated by Django 6.0 on 2026-08-26 02:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0012_question_choice_notes'),
        ('mypage', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WrongAnswerExclusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='제외한 날')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wrong_exclusions', to='exam.question', verbose_name='문제')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wrong_exclusions', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '오답노트 제외',
                'verbose_name_plural': '오답노트 제외',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'question')},
            },
        ),
    ]
