# Generated by Django 6.0 on 2026-02-03 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_model', models.CharField(choices=[('gemini-3-pro-preview', 'Gemini 3 Pro Preview ($2/$12 per 1M)'), ('gemini-3-flash-preview', 'Gemini 3 Flash Preview ($0.5/$3 per 1M)'), ('gemini-2.0-flash-exp', 'Gemini 2.0 Flash Exp (Legacy)')], default='gemini-3-pro-preview', max_length=50, verbose_name='나무주치의 모델')),
                ('textbook_model', models.CharField(choices=[('gemini-3-pro-preview', 'Gemini 3 Pro Preview ($2/$12 per 1M)'), ('gemini-3-flash-preview', 'Gemini 3 Flash Preview ($0.5/$3 per 1M)'), ('gemini-2.0-flash-exp', 'Gemini 2.0 Flash Exp (Legacy)')], default='gemini-3-flash-preview', max_length=50, verbose_name='기본서 모델')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '사이트 설정',
                'verbose_name_plural': '사이트 설정',
            },
        ),
    ]
