# Generated by Django 6.0 on 2026-08-26 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='chat_model',
            field=models.CharField(choices=[('gemini-3.7-flash', 'Gemini 3.7 Flash (권장)'), ('gemini-3.1-pro-preview', 'Gemini 3.1 Pro Preview (고품질·느림)'), ('gemini-3-flash-preview', 'Gemini 3 Flash Preview'), ('gemini-2.5-pro', 'Gemini 2.5 Pro'), ('gemini-2.5-flash', 'Gemini 2.5 Flash ($0.15/$0.60 per 1M)'), ('gemini-2.5-flash-lite', 'Gemini 2.5 Flash Lite (가장 저렴)')], default='gemini-3.7-flash', max_length=50, verbose_name='나무주치의 모델'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='textbook_model',
            field=models.CharField(choices=[('gemini-3.7-flash', 'Gemini 3.7 Flash (권장)'), ('gemini-3.1-pro-preview', 'Gemini 3.1 Pro Preview (고품질·느림)'), ('gemini-3-flash-preview', 'Gemini 3 Flash Preview'), ('gemini-2.5-pro', 'Gemini 2.5 Pro'), ('gemini-2.5-flash', 'Gemini 2.5 Flash ($0.15/$0.60 per 1M)'), ('gemini-2.5-flash-lite', 'Gemini 2.5 Flash Lite (가장 저렴)')], default='gemini-3.7-flash', max_length=50, verbose_name='기본서 모델'),
        ),
    ]
