# Generated by Django 5.2.8 on 2026-01-16 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersession',
            name='last_page_name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='마지막 페이지'),
        ),
    ]
