# Generated by Django 6.0 on 2026-07-30 13:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_add_last_page_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='출석일')),
                ('checked_at', models.DateTimeField(auto_now_add=True, verbose_name='체크 시각')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('user_agent', models.CharField(blank=True, default='', max_length=500, verbose_name='기기 정보')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '출석',
                'verbose_name_plural': '출석',
                'ordering': ['-date', '-checked_at'],
                'indexes': [models.Index(fields=['-date'], name='accounts_at_date_7197b7_idx')],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
