# Generated by Django 6.0 on 2026-07-31 15:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_attendance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SignupApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='승인 토큰')),
                ('status', models.CharField(choices=[('pending', '대기'), ('approved', '승인'), ('rejected', '거부')], db_index=True, default='pending', max_length=10, verbose_name='상태')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='가입 IP')),
                ('user_agent', models.CharField(blank=True, default='', max_length=500, verbose_name='기기 정보')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='요청 시각')),
                ('decided_at', models.DateTimeField(blank=True, null=True, verbose_name='처리 시각')),
                ('decided_by', models.CharField(blank=True, default='', max_length=150, verbose_name='처리자')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='signup_approval', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '가입 승인',
                'verbose_name_plural': '가입 승인',
                'ordering': ['-created_at'],
            },
        ),
    ]
