# Generated by Django 6.0 on 2026-08-02 14:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TreeCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='코스명')),
                ('description', models.CharField(blank=True, default='', max_length=200, verbose_name='설명')),
                ('order', models.IntegerField(default=0, verbose_name='정렬 순서')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '수목 식별 코스',
                'verbose_name_plural': '수목 식별 코스',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TreeQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='treeid/', verbose_name='수목 사진')),
                ('order', models.IntegerField(default=0, verbose_name='순번')),
                ('name', models.CharField(blank=True, default='', max_length=200, verbose_name='수목명')),
                ('description', models.TextField(blank=True, default='', verbose_name='특징 설명')),
                ('source_key', models.CharField(blank=True, db_index=True, default='', max_length=200, verbose_name='원본 식별자')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='treeid.treecourse', verbose_name='코스')),
            ],
            options={
                'verbose_name': '수목 식별 문제',
                'verbose_name_plural': '수목 식별 문제',
                'ordering': ['course', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TreeBookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록 시각')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tree_bookmarks', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='treeid.treequestion', verbose_name='문제')),
            ],
            options={
                'verbose_name': '관심 수목',
                'verbose_name_plural': '관심 수목',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'question')},
            },
        ),
    ]
