# Generated by Django 5.2.8 on 2026-01-05 07:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='교재명')),
                ('subject', models.CharField(max_length=100, verbose_name='과목')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '교재',
                'verbose_name_plural': '교재',
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, verbose_name='목차 번호')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('level', models.IntegerField(default=1, verbose_name='단계')),
                ('order', models.IntegerField(default=0, verbose_name='순서')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='practice.book', verbose_name='교재')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='practice.chapter', verbose_name='상위 목차')),
            ],
            options={
                'verbose_name': '목차',
                'verbose_name_plural': '목차',
                'ordering': ['book', 'order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='PracticeQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=1, verbose_name='문제 번호')),
                ('content', models.TextField(verbose_name='문제 내용')),
                ('choice1', models.CharField(max_length=500, verbose_name='선지 1')),
                ('choice2', models.CharField(max_length=500, verbose_name='선지 2')),
                ('choice3', models.CharField(max_length=500, verbose_name='선지 3')),
                ('choice4', models.CharField(max_length=500, verbose_name='선지 4')),
                ('choice5', models.CharField(max_length=500, verbose_name='선지 5')),
                ('answer', models.IntegerField(verbose_name='정답')),
                ('explanation', models.TextField(blank=True, verbose_name='해설')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='practice.chapter', verbose_name='목차')),
            ],
            options={
                'verbose_name': '연습문제',
                'verbose_name_plural': '연습문제',
                'ordering': ['chapter', 'number'],
            },
        ),
        migrations.CreateModel(
            name='PracticeAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_answer', models.IntegerField(verbose_name='선택한 답')),
                ('is_correct', models.BooleanField(default=False, verbose_name='정답 여부')),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_attempts', to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='practice.practicequestion')),
            ],
            options={
                'verbose_name': '풀이 기록',
                'verbose_name_plural': '풀이 기록',
                'ordering': ['-attempted_at'],
            },
        ),
    ]
