# Generated by Django 5.2.8 on 2026-01-05 23:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChapterContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='내용')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_contents', to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
                ('chapter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='content', to='practice.chapter', verbose_name='목차')),
            ],
            options={
                'verbose_name': '학습 컨텐츠',
                'verbose_name_plural': '학습 컨텐츠',
            },
        ),
    ]
