# Generated by Django 6.0 on 2026-02-12 04:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0003_alter_comment_options'),
        ('practice', '0002_chaptercontent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChapterPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linked_at', models.DateTimeField(auto_now_add=True, verbose_name='연결일시')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linked_posts', to='practice.chapter', verbose_name='목차')),
                ('linked_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='연결한 사람')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linked_chapters', to='bbs.post', verbose_name='게시글')),
            ],
            options={
                'verbose_name': '목차-게시글 연결',
                'verbose_name_plural': '목차-게시글 연결',
                'ordering': ['-linked_at'],
                'unique_together': {('chapter', 'post')},
            },
        ),
    ]
