# Generated by Django 6.0 on 2026-08-27 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0003_chapterpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='practicequestion',
            name='choice_notes',
            field=models.JSONField(blank=True, default=dict, help_text='{"1": "설명", ...} 형태. 기출문제와 같은 구조', verbose_name='선지별 답변'),
        ),
    ]
