# Generated by Django 5.2.8 on 2026-01-08 01:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='과목명')),
            ],
            options={
                'verbose_name': '과목',
                'verbose_name_plural': '과목',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=200, unique=True, verbose_name='용어')),
                ('content', models.TextField(verbose_name='설명')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('subjects', models.ManyToManyField(blank=True, related_name='terms', to='glossary.subject', verbose_name='관련 과목')),
            ],
            options={
                'verbose_name': '용어',
                'verbose_name_plural': '용어',
                'ordering': ['word'],
            },
        ),
        migrations.CreateModel(
            name='TermReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('chapter_content', 'ChapterContent'), ('question', 'Question'), ('practice_question', 'PracticeQuestion')], max_length=50, verbose_name='출처 유형')),
                ('source_id', models.IntegerField(verbose_name='출처 ID')),
                ('source_title', models.CharField(blank=True, max_length=300, verbose_name='출처 제목')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='glossary.term', verbose_name='용어')),
            ],
            options={
                'verbose_name': '용어 참조',
                'verbose_name_plural': '용어 참조',
                'unique_together': {('term', 'source_type', 'source_id')},
            },
        ),
    ]
