# Generated by Django 5.2.8 on 2026-01-15 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glossary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='term',
            name='canonical_term',
            field=models.ForeignKey(blank=True, help_text='유사어인 경우, 대표 용어를 선택하세요', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='synonyms', to='glossary.term', verbose_name='대표 용어'),
        ),
    ]
