# Generated by Django 6.0 on 2026-08-06 07:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='시험명')),
                ('subject', models.CharField(choices=[('tree', '수목'), ('disease', '병해'), ('pest', '해충')], max_length=10, verbose_name='학습대상')),
                ('kind', models.CharField(choices=[('always', '상시시험'), ('live', '실시간 시험')], default='always', max_length=10, verbose_name='시험유형')),
                ('answer_format', models.CharField(choices=[('choice', '객관식형'), ('typing', '주관식형')], default='choice', max_length=10, verbose_name='선택유형')),
                ('question_count', models.IntegerField(default=20, verbose_name='문항 수')),
                ('time_limit_min', models.IntegerField(default=0, help_text='0이면 제한 없음', verbose_name='제한 시간(분)')),
                ('start_at', models.DateTimeField(blank=True, null=True, verbose_name='시작 시각')),
                ('end_at', models.DateTimeField(blank=True, null=True, verbose_name='종료 시각')),
                ('is_active', models.BooleanField(default=True, verbose_name='공개')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_dvd_exams', to=settings.AUTH_USER_MODEL, verbose_name='등록자')),
            ],
            options={
                'verbose_name': 'DVD 시험',
                'verbose_name_plural': 'DVD 시험',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExamAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='시작 시각')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='제출 시각')),
                ('score', models.IntegerField(default=0, verbose_name='맞은 개수')),
                ('total', models.IntegerField(default=0, verbose_name='문항 수')),
                ('auto_submitted', models.BooleanField(default=False, verbose_name='시간 종료 제출')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='dvdexam.exam', verbose_name='시험')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dvd_exam_attempts', to=settings.AUTH_USER_MODEL, verbose_name='응시자')),
            ],
            options={
                'verbose_name': 'DVD 시험 응시',
                'verbose_name_plural': 'DVD 시험 응시',
                'ordering': ['-started_at'],
                'unique_together': {('exam', 'user')},
            },
        ),
        migrations.CreateModel(
            name='ExamQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0, verbose_name='번호')),
                ('source_id', models.IntegerField(verbose_name='원본 문제 ID')),
                ('image_url', models.CharField(max_length=300, verbose_name='사진 경로')),
                ('answer', models.CharField(max_length=200, verbose_name='정답')),
                ('choices', models.JSONField(blank=True, default=list, verbose_name='보기 5개')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='dvdexam.exam', verbose_name='시험')),
            ],
            options={
                'verbose_name': 'DVD 시험 문제',
                'verbose_name_plural': 'DVD 시험 문제',
                'ordering': ['exam', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ExamAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('given', models.CharField(blank=True, default='', max_length=200, verbose_name='응답')),
                ('is_correct', models.BooleanField(default=False, verbose_name='정답 여부')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='dvdexam.examattempt', verbose_name='응시')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='dvdexam.examquestion', verbose_name='문제')),
            ],
            options={
                'verbose_name': 'DVD 시험 응답',
                'verbose_name_plural': 'DVD 시험 응답',
                'ordering': ['question__order'],
                'unique_together': {('attempt', 'question')},
            },
        ),
    ]
