# Generated by Django 6.0 on 2026-08-06 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dvdexam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='examattempt',
            name='last_saved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='마지막 저장'),
        ),
    ]
