# Generated by Django 6.0 on 2026-08-13 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dvdexam', '0002_examattempt_last_saved_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='examattempt',
            name='retrying_since',
            field=models.DateTimeField(blank=True, help_text='값이 있으면 재응시 진행 중', null=True, verbose_name='재응시 시작'),
        ),
    ]
