# Generated by Django 6.0 on 2026-08-17 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dvdexam', '0003_examattempt_retrying_since'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='examanswer',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='examanswer',
            name='is_retry',
            field=models.BooleanField(default=False, help_text='재응시 중에 푼 답. 제출하면 확정분이 된다', verbose_name='재응시분'),
        ),
        migrations.AlterUniqueTogether(
            name='examanswer',
            unique_together={('attempt', 'question', 'is_retry')},
        ),
    ]
