# Generated by Django 6.0 on 2026-07-30 13:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PestCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='코스명')),
                ('description', models.CharField(blank=True, default='', max_length=200, verbose_name='설명')),
                ('order', models.IntegerField(default=0, verbose_name='정렬 순서')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '해충 식별 코스',
                'verbose_name_plural': '해충 식별 코스',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PestAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('choice', '객관식'), ('typing', '주관식')], default='choice', max_length=10, verbose_name='모드')),
                ('total_count', models.IntegerField(default=0, verbose_name='문제 수')),
                ('correct_count', models.IntegerField(default=0, verbose_name='정답 수')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='시작 시각')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='완료 시각')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pest_attempts', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='pestid.pestcourse', verbose_name='코스')),
            ],
            options={
                'verbose_name': '해충 식별 도전',
                'verbose_name_plural': '해충 식별 도전',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='PestQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='pestid/', verbose_name='해충 사진')),
                ('order', models.IntegerField(default=0, verbose_name='순번')),
                ('name', models.CharField(blank=True, default='', max_length=200, verbose_name='해충명')),
                ('occurrence', models.CharField(blank=True, default='', max_length=200, verbose_name='연발생횟수')),
                ('overwinter', models.CharField(blank=True, default='', max_length=200, verbose_name='월동태')),
                ('host', models.CharField(blank=True, default='', max_length=200, verbose_name='여름기주')),
                ('source_key', models.CharField(blank=True, db_index=True, default='', help_text='임포트 시 중복 방지용 (원본 파일명 등)', max_length=200, verbose_name='원본 식별자')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='pestid.pestcourse', verbose_name='코스')),
            ],
            options={
                'verbose_name': '해충 식별 문제',
                'verbose_name_plural': '해충 식별 문제',
                'ordering': ['course', 'order', 'id'],
            },
        ),
    ]
