# Generated by Django 6.0 on 2026-07-31 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pestid', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pestquestion',
            name='taxon_family',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='과'),
        ),
        migrations.AddField(
            model_name='pestquestion',
            name='taxon_order',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='목'),
        ),
    ]
