# Generated by Django 6.0 on 2026-07-31 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pestid', '0002_pestquestion_taxon_family_pestquestion_taxon_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='pestquestion',
            name='exam_note',
            field=models.CharField(blank=True, default='', help_text='예: 5회(여름기주) · 9회(월동태) · 11회(여름기주)', max_length=200, verbose_name='기출 회차'),
        ),
        migrations.AddField(
            model_name='pestquestion',
            name='exam_stars',
            field=models.IntegerField(db_index=True, default=0, verbose_name='기출 중요도'),
        ),
    ]
