# Generated by Django 6.0 on 2026-07-31 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pestid', '0003_pestquestion_exam_note_pestquestion_exam_stars'),
    ]

    operations = [
        migrations.AddField(
            model_name='pestquestion',
            name='main_host',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='기주'),
        ),
        migrations.AddField(
            model_name='pestquestion',
            name='overwinter_place',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='월동처'),
        ),
    ]
