# Generated by Django 5.2.8 on 2025-12-13 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notebookhistory',
            name='subject',
            field=models.CharField(default='기본', max_length=50, verbose_name='과목'),
        ),
    ]
